### ISSUE TITLE
Add multilanguage option (Installer and languages folders)

### ISSUE THREAD

**Issue by bovirus** [Timthreetwelve/HWiNFO-VSB-Viewer#2]
@Timthreetwelve 

Could you please enable multilanguage installer and languages as for other programs?

Thanks.

**Comment by Timthreetwelve** [comment]
@bovirus 

I got a start on this today. I pushed what I had completed. Still more work to do but the en-US language file is close to complete. It's mostly strings that have been in the other apps.

The Inno Setup script is OLD. If you feel like it, you could update it to work like the others. If you just want to add the other languages, that's cool too.

I have a busy day tomorrow; I might not get a chance to look at anything until late in the day. BTW it was time-change weekend here, so I'm UTC -6:00 again.

Tim

**Comment by bovirus** [comment]
@Timthreetwelve 

- AppVersion

Some question on your apps.
Why in some Inno Setup script yopu get appVersion form maine xe file and sometimes not?
For me get the AppVersion from main exe file is the best solution and I propose you to use it for all your app,

- Copyright start/end (current) year

In Copyright message my idea for copyright message is

"(c) StartingCopyrightYear-EndCopyrightYear Author" (ex. "(c) 2017-2023 Tim Kennedy")

where "EndCopyrightYear" is always current year.

Or did you prefer just "(c) EndCopyrightYear Author" (ex. "(c) 2023 Tim Kennedy")

If you like "(c) StartingCopyrightYear-EndCopyrightYear Author" (my personal choice) I should get the info about StartingCopyrightYear for each of your apps

GetMyIP
HWiNFO-VSB-Viewer
TimVer
Windows Update Viewer

**Comment by Timthreetwelve** [comment]
When you say:
>For me get the AppVersion from main exe file is the best solution and I propose you to use it for all your app,

do you mean the differences between this method `GetStringFileInfo(MySourceDir + "\" + MyAppExeName, "FileVersion")` this method? `GetStringFileInfo("D:\Visual Studio\Source\Prod\TimVer\TimVer\bin\Publish\TimVer.exe", "FileVersion")` and this method? `GetVersionNumbersString(MySourceDir + "\" + MyAppExeName)`

Until looking at four scripts today I didn't realize that I was using three different methods. They all seem to work, but I'm a huge fan of consistency, so you pick the one that you feel is best and we can change all the installers to use the same method.

Regarding the copyright message, are you referring to the AppCopyright statement in the installer script or the copyright shown in the about page in the app. or the copyright that appears in the properties of the exe file? 

![explorer_2023-11-06_17-05-31](https://github.com/Timthreetwelve/HWiNFO-VSB-Viewer/assets/43152358/8ef2d1c4-161f-4cd0-99e0-4a7525b69c58)

**Comment by bovirus** [comment]
@Timthreetwelve 

I'm referring to text strign showed in instalelr exe file -> right click -> properties -> Copyright info

- GetStringFileInfo

GetStringFileInfo(MySourceDir + "\" + MyAppExeName, "FileVersion")
GetStringFileInfo("D:\Visual Studio\Source\Prod\TimVer\TimVer\bin\Publish\TimVer.exe", "FileVersion")

are the same.
The difference between first and secondo is usung direct value or varoiables.
GetStringFileInfo it's a common instruction for pre-processor to get one or mroe value of file.

GetStringFileInfo info - https://jrsoftware.org/ispphelp/index.php?topic=getstringfileinfo

- GetVersionNumbersString

GetVersionNumbersString(MySourceDir + "\" + MyAppExeName)

GetVersionNumbersString - (https://jrsoftware.org/ishelp/index.php?topic=isxfunc_getversionnumbersstring)

Is the typical instruction that get only versionnumber by exe file.

**Comment by bovirus** [comment]
@Timthreetwelve 

Some feedback

For me "DisableWelcomePage=no" should be commented

;DisableWelcomePage=no

In this way you can see on top left app name + version in eacjh step oif the installer (but skip welcome page)
If you leave as it is yous ee on top left only app name (without version)

About "SourceDir={#MySourceDir}" pelase take care that is redunding set nebecauise it move the source dir from .iss file to new path

Then

Source: "{#MySourceDir}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion

become

Source: "{#SourceDir}{#MySourceDir}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion

For me should be

;"SourceDir={#MySourceDir}"

**Comment by Timthreetwelve** [comment]
@bovirus 

My internet was down a good portion of the day. It might be the best thing to happen to me for a while.

If the welcome page is disabled, then the statement that .NET 6 is required isn't displayed. If I must choose between the version number and the .NET statement, the .NET statement wins.

I have personally grown to dislike the need to click through an installer license page that I never read anyway. I used them at one time and have decided that they don't belong in my installers. The license is available in the repo, is included with the apps and is available from the About page. 

I'm releasing HWiNFOVSBViewer verion 0.3.0 tonight. If they are ready, I would also like to release the next versions of WUView and GetMyIP this week.

**Comment by bovirus** [comment]
@Timthreetwelve 

Please release new versions.
