### ISSUE TITLE
Enhancement Request - 0.3.0 - GUI improvments

### ISSUE THREAD

**Issue by bovirus** [Timthreetwelve/HWiNFO-VSB-Viewer#7]
### Brief summary of your request

GUUI improvements

### Request details

@Timthreetwelve 

- GUI issues
 
Please check screenshots for details

![image](https://github.com/Timthreetwelve/HWiNFO-VSB-Viewer/assets/1262554/f8a35c4f-9749-4fa7-b34b-c123aec18a39)

-  GUi unatrsnaltyd strings

Please check screenshots for details

![image](https://github.com/Timthreetwelve/HWiNFO-VSB-Viewer/assets/1262554/561caf5d-bf45-4544-a566-ff34bc5ad3f7)

![image](https://github.com/Timthreetwelve/HWiNFO-VSB-Viewer/assets/1262554/c24e00df-54e5-4a6a-bc95-ab0fcc53a84f)

**Comment by Timthreetwelve** [comment]
Fixed!

"Filter" was already in the language file. Line 53. I used your translation from WUView to fix it.

``` XML
    <!--  Filter Box Hint Text  -->
    <sys:String x:Key="FilterHint">Filtro</sys:String>
```

**Comment by bovirus** [comment]
@Timthreetwelve 

Thanks.
