### ISSUE TITLE
Enhancement Request - Add nel languages  (NL/SK)

### ISSUE THREAD

**Issue by bovirus** [Timthreetwelve/HWiNFO-VSB-Viewer#8]
### Brief summary of your request

Add new languages

### Request details

@Vaso73
@CMTrix

Could you pelase translate the application in your language

Master english language file

- View
https://github.com/Timthreetwelve/HWiNFO-VSB-Viewer/blob/main/HWiNFOVSBViewer/Languages/Strings.en-US.xaml

-  Download
https://raw.githubusercontent.com/Timthreetwelve/HWiNFO-VSB-Viewer/main/HWiNFOVSBViewer/Languages/Strings.en-US.xaml

Thanks.

**Comment by CMTriX** [comment]
[Strings.nl-NL.xaml.txt](https://github.com/Timthreetwelve/HWiNFO-VSB-Viewer/files/13294798/Strings.nl-NL.xaml.txt)

**Comment by bovirus** [comment]
@CMTriX 

Please translate these string for the installer

Welcome to [name] Setup
Do you want to remove the settings and history files and registry entries?%n%nSelect "No" if you plan to reinstall the program.

**Comment by Vaso73** [comment]
[Strings.sk-SK.zip](https://github.com/Timthreetwelve/HWiNFO-VSB-Viewer/files/13296902/Strings.sk-SK.zip)

**Comment by CMTriX** [comment]
Please translate these string for the installer
Vertaal deze waardes voor het installatieprogramma alstublieft

Welcome to [name] Setup
Welkom bij het [name] installatieprogramma

Do you want to remove the settings and history files and registry entries?%n%nSelect "No" if you plan to reinstall the program.
Wilt u de instellingen, data bestanden en registerwaarden verwijderen?%n%nKies 'NEE' als u het programma opnieuw wilt installeren.

Completing [name] Setup
Afronden van installatie [name]

View the ReadMe file
Bekijk het leesmij bestand

is running, please close it to continue with the installation.
is gestart, sluit het om verder te gaan met de installatie

Do you want to remove the settings files?%nSelect 'No' if you plan on reinstalling.
Wilt u de instellingen verwijderen?%n%nKies 'NEE' als u het programma opnieuw wilt installeren.

**Comment by bovirus** [comment]
@Vaso73

- Please transate follow strings for installer

Welcome to [name] Setup
Completing [name] Setup
Do you want to remove the settings and history files and registry entries?%n%nSelect "No" if you plan to reinstall the program.

**Comment by Timthreetwelve** [comment]
I added 2 strings and updated the text in another at 18:14 UTC. Changes are at the end of the en-US file.

**Comment by Timthreetwelve** [comment]
When updating a language file, please be careful not to duplicate a key. It's very easy to do so when updating an existing key.

Thanks,
Tim
